---
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 23]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Check ${{ matrix.node-version }}
        run: npm run check
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
